name: Kernel Config - A12 4.14

permissions:
  contents: write  # Allow writing to repository contents
  actions: write   # Allows triggering actions

on:
  workflow_call:
    inputs: {}

jobs:
  build-kernels-a12:
    name: "4.14.${{ matrix.sub_level }}-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        # Deprecated series (Android 12 - 4.14)
        - sub_level: "190"
          os_patch_level: "2021-04"
        - sub_level: "190"
          os_patch_level: "2021-05"
        - sub_level: "190"
          os_patch_level: "2021-06"
        - sub_level: "190"
          os_patch_level: "2021-07"
        - sub_level: "190"
          os_patch_level: "2021-08"
        - sub_level: "190"
          os_patch_level: "2021-09"
        - sub_level: "190"
          os_patch_level: "2021-10"
        - sub_level: "190"
          os_patch_level: "2021-11"
        - sub_level: "190"
          os_patch_level: "2021-12"
        - sub_level: "190"
          os_patch_level: "2022-01"
        - sub_level: "190"
          os_patch_level: "2022-02"
        - sub_level: "190"
          os_patch_level: "2022-03"
        - sub_level: "190"
          os_patch_level: "2022-04"
        - sub_level: "190"
          os_patch_level: "2022-05"
        - sub_level: "190"
          os_patch_level: "2022-06"
        - sub_level: "190"
          os_patch_level: "2022-07"
        - sub_level: "190"
          os_patch_level: "2022-08"
        - sub_level: "190"
          os_patch_level: "2022-09"
        - sub_level: "190"
          os_patch_level: "2022-10"
        - sub_level: "190"
          os_patch_level: "2022-11"
        - sub_level: "190"
          os_patch_level: "2022-12"
        - sub_level: "190"
          os_patch_level: "2023-01"
        - sub_level: "190"
          os_patch_level: "2023-02"
        - sub_level: "190"
          os_patch_level: "2023-03"
        - sub_level: "190"
          os_patch_level: "2023-04"
        - sub_level: "190"
          os_patch_level: "2023-05"
        - sub_level: "190"
          os_patch_level: "2023-06"
        - sub_level: "190"
          os_patch_level: "2023-07"
        - sub_level: "190"
          os_patch_level: "2023-08"
        - sub_level: "190"
          os_patch_level: "2023-09"
        - sub_level: "190"
          os_patch_level: "2023-10"
        - sub_level: "190"
          os_patch_level: "2023-11"
        - sub_level: "190"
          os_patch_level: "2023-12"
        - sub_level: "190"
          os_patch_level: "2024-01"
        - sub_level: "190"
          os_patch_level: "2024-02"
        - sub_level: "190"
          os_patch_level: "2024-03"
        - sub_level: "190"
          os_patch_level: "2024-04"
        - sub_level: "190"
          os_patch_level: "2024-05"
        - sub_level: "190"
          os_patch_level: "2024-06"
        - sub_level: "190"
          os_patch_level: "2024-07"
        - sub_level: "190"
          os_patch_level: "2024-08"
        - sub_level: "190"
          os_patch_level: "2024-09"
        - sub_level: "190"
          os_patch_level: "2024-10"
        - sub_level: "190"
          os_patch_level: "2024-11"
        - sub_level: "190"
          os_patch_level: "2024-12"
        - sub_level: "190"
          os_patch_level: "2025-01"
        - sub_level: "190"
          os_patch_level: "2025-02"
        - sub_level: "190"
          os_patch_level: "2025-03"
        - sub_level: "190"
          os_patch_level: "2025-04"
        - sub_level: "190"
          os_patch_level: "2025-05"
        - sub_level: "190"
          os_patch_level: "2025-06"
        - sub_level: "190"
          os_patch_level: "2025-07"
        - sub_level: "190"
          os_patch_level: "2025-08"
        - sub_level: "190"
          os_patch_level: "2025-09"
        # LTS meta
        - sub_level: "X"
          os_patch_level: "lts"
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android12"
      kernel_version: "4.14"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
